#######
# Compiled from /examples/functions/advanced Modal.mcscript
# to .//examples/functions/advanced_modal.mcfunction
#
# Generated by Minecraft Script for 1.13
######

say Hello You! A message from Stevertus
say Hello Player! A message from me

# overriden modal
say Hello Stevertus