#######
# Compiled from /examples/functions/arrays.mcscript
# to .//examples/functions/arrays.mcfunction
#
# Generated by Minecraft Script for 1.13
######

say value
say no value2

# calling it with Inline Array
say value
# with defaults

say value
say value2