#######
# Compiled from .//functions/arrays.mcscript
# to .//functions/arrays.mcfunction
#
# Generated by Minecraft Script for 1.16
######

say value
say no value2

# calling it with Inline Array
say value
# with defaults

say value
say value2