#######
# Compiled from .//functions/boolean.mcscript
# to .//functions/boolean.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @e[tag=mcscriptTags] add isCool
tag @e[tag=mcscriptTags] remove isCool
execute if entity @e[tag=mcscriptTags,tag=isCool] run say he is cool

tag @s add isBad
tag @s remove isBad
execute if entity @s[tag=isBad] run say he is bad

# Extended from .//functions/boolean.mcscript
# to .//functions/boolean.mcfunction
functions/mcscript/load
# please do not touch this file!
# it is used by the compiler!
execute unless entity @e[tag=mcscriptTags] at @p run summon armor_stand ~ ~ ~ {Tags:[mcscriptTags],Invisible:1,Invulnerable:1,NoGravity:1}
