#######
# Compiled from /examples/functions/comments.mcscript
# to .//examples/functions/comments.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#file ./comments
# this file is contentless, it is just a demonstration for comments
# single line transfare comment. This comment will be transfared to the compiled result function
say hey