#######
# Compiled from /examples/functions/consts.mcscript
# to .//examples/functions/consts.mcfunction
#
# Generated by Minecraft Script for 1.13
######

say some value here
say some value here

execute if score @s matches 5 run tellraw @a [{"text":"console => ","color":"aqua"},{"text":"is five","color":"white"}]
