#######
# Compiled from .//functions/consts.mcscript
# to .//functions/consts.mcfunction
#
# Generated by Minecraft Script for 1.16
######

say some string here
say some value here

execute if score @s matches 5 run tellraw @a [{"text":"console => ","color":"aqua"},{"text":"is five","color":"white"}]
