#######
# Compiled from .//functions/forEach.mcscript
# to .//functions/foreach.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# basic loop
scoreboard players set i i -5
execute if score i i matches ..4 run function :mcscript/foreach2
# faculty
scoreboard players set result result 1
scoreboard players set j j 2
execute if score j j matches ..10 run function :mcscript/foreach3