#######
# Compiled from .//functions/forEach.mcscript
# to .//functions/foreach.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# basic loop
scoreboard players set i i 0
execute if score i i matches ..9 run function :mcscript/foreach1
# faculty
scoreboard players set result result 1
scoreboard players set j j 2
execute if score j j matches ..10 run function :mcscript/foreach2