#######
# Compiled from .//functions/global.mcscript
# to .//functions/global.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set global1 global1 5


# Extended from .//functions/global.mcscript
# to .//functions/global.mcfunction
functions/mcscript/load
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add global1 dummy
