#######
# Compiled from examples/functions/groups.mcscript
# to examples/functions/groups.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @s run say hey
execute as @s at @s run say hey
execute positioned ~ ~1 ~ run setblock ~ ~ ~ stone
execute in overworld run say Im in the overworld