#######
# Compiled from .//functions/Hello World.mcscript
# to .//functions/hello_world.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"Hello World!","color":"white"}]