#######
# Compiled from /examples/functions/Hello World.mcscript
# to .//examples/functions/hello_world.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"Hello World!","color":"white"}]