#######
# Compiled from functions/jsmodal.mcscript
# to functions/jsmodal.mcfunction
#
# Generated by Minecraft Script for 1.13
######


say Hallo Welt!
summon minecraft:zombie

say Hallo Welt!
summon minecraft:zombie
