#######
# Compiled from /examples/functions/maps.mcscript
# to .//examples/functions/maps.mcfunction
#
# Generated by Minecraft Script for 1.13
######

say value
say no value2

say undefined

say value
say undefined