#######
# Compiled from .//functions/maps.mcscript
# to .//functions/maps.mcfunction
#
# Generated by Minecraft Script for 1.16
######

say value
say no value2

say undefined

say value
say undefined