#######
# Compiled from .//functions/Operators.mcscript
# to .//functions/operators.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# and operator
execute if cond1 if cond2 run say condition 1 and condition 2 is true

# or operator
execute if cond1 run say condition 1 or condition 2 is true
execute if cond2 run say condition 1 or condition 2 is true

# or operator as list
execute if cond1 run say condition 1 or condition 2 is true
execute if cond2 run say condition 1 or condition 2 is true

# and or combined
execute if cond1 if cond2 run say condition 1 and condition 2 or cond3 is true
execute if cond3 run say condition 1 and condition 2 or cond3 is true

# not and
execute if cond1 run say condition 1 and not condition 2 is true
