#######
# Compiled from examples/functions/raycasting.mcscript
# to examples/functions/raycast.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast4 mcscript_raycast 0
execute positioned ~ ~1 ~ run function examples:mcscript/raycast4
