#######
# Compiled from .//functions/raycasting.mcscript
# to .//functions/raycast.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set raycast4 mcscript_raycast 0
execute positioned ~ ~1 ~ run function :mcscript/raycast4
