#######
# Compiled from .//functions/raycasting.mcscript
# to .//functions/raycast.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast4 raycast4 0
execute positioned ~ ~1 ~ run function :mcscript/raycast4
