#######
# Compiled from examples/functions/shortforms.mcscript
# to examples/functions/shortforms.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#do something as everybody
execute as @a run say i'm also existing
#do something at everybody
execute at @a run summon lightning_bolt ~ ~ ~
#do sonthing as and at everybody
execute as @a at @s run summon lightning_bolt ~ ~ ~
execute as @s at @s run say A lightning_bolt hit me
