#######
# Compiled from .//functions/function.mcscript
# to .//functions/test.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//functions/function.mcscript
say function