#######
# Compiled from /examples/functions/function.mcscript
# to .//examples/functions/test.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//examples/functions/function.mcscript
say function