#######
# Compiled from /examples/functions/while-Loops.mcscript
# to .//examples/functions/while.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=loop] run function examples:mcscript/while3