#######
# Compiled from .//functions/while-Loops.mcscript
# to .//functions/while.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute if entity @s[tag=loop] run function :mcscript/while5