#######
# Compiled from /lib/modals/basic.mcscript
# to .//lib/modals/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######


tellraw @a [{"text":"console => ","color":"aqua"},{"score":{"name":"he","objective": "hello"},"color":"white"}]