const fs = require("fs");
const path = require("path");

let packid = "";
genNew = function (name, pack_format = 6) {
	packid = name.toLowerCase().replace(" ", "_");
	// mcmeta file
	genFile(
		"pack.mcmeta",
		`
{
	"pack": {
		"pack_format": ${pack_format},
		"description": "${packid} vanilla pack generated by mcscript"
	}
}`
	);
	// load event
	genFile(
		"data/minecraft/tags/functions/load.json",
		`
{
	"values":[
		"${packid}:load"
	]
}`
	);
	// tick event
	genFile(
		"data/minecraft/tags/functions/tick.json",
		`
{
	"values":[
		"${packid}:tick"
	]
}`
	);
	// load.mcscript
	genFile(
		`data/${packid}/scripts/load.mcscript`,
		`#file: ./load

// here goes your load content`
	);
	// load mcscript
	genFile(
		`data/${packid}/functions/mcscript/load.mcfunction`,
		`
# please do not touch this file!
# it is used by the compiler!`
	);
	// tick.mcscript
	genFile(
		`data/${packid}/scripts/tick.mcscript`,
		`
#file: ./tick
// here goes your tick content
// executes 20 times a second`
	);
	ensureDirectoryExistence(`${packid}/data/${packid}/advancements/test.js`);
	ensureDirectoryExistence(`${packid}/data/${packid}/tags/test.js`);
};

function ensureDirectoryExistence(filePath) {
	const dirname = path.dirname(filePath);
	if (fs.existsSync(dirname)) {
		return true;
	}
	ensureDirectoryExistence(dirname);
	fs.mkdirSync(dirname);
}

function genFile(file, data) {
	file = packid + "/" + file;
	ensureDirectoryExistence(file);
	fs.writeFile(file, data, (err) => {
		if (err) throw err;
		console.log("\x1b[36m", "Generated ", "\x1b[33m", file, "\x1b[0m");
	});
}

exports.new = genNew;
