#######
# Compiled from /examples/functions/do-while-Loops.mcscript
# to examples/functions/mcscript/dowhile6.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"commands","color":"white"}]
execute if entity @s[tag=!mcscriptStop] if entity @s[tag=loop] run function examples:mcscript/dowhile6
tag @s[tag=mcscriptStop] remove mcscriptStop
