#######
# Compiled from .//functions/do-while-Loops.mcscript
# to functions/mcscript/dowhile1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"commands","color":"white"}]
execute if entity @s[tag=!mcscriptStop] if entity @s[tag=loop] run function :mcscript/dowhile1
tag @s[tag=mcscriptStop] remove mcscriptStop
