#######
# Compiled from /examples/functions/forEach.mcscript
# to examples/functions/mcscript/foreach5.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation result result *= i i
scoreboard players add j j 1
execute if entity @s[tag=!mcscriptStop] if score j j matches ..10 run function examples:mcscript/foreach5
tag @s[tag=mcscriptStop] remove mcscriptStop
