#######
# Compiled from /examples/functions/forEach.mcscript
# to examples/functions/mcscript/foreach5.mcfunction
#
# Generated by Minecraft Script for 1.13
######
say hey
scoreboard players add i i 1
execute if entity @s[tag=!mcscriptStop] if score i i matches ..9 run function examples:mcscript/foreach5
tag @s[tag=mcscriptStop] remove mcscriptStop
