#######
# Compiled from .//functions/forEach.mcscript
# to functions/mcscript/foreach1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
say hey
scoreboard players add i i 1
execute if entity @s[tag=!mcscriptStop] if score i i matches ..9 run function :mcscript/foreach1
tag @s[tag=mcscriptStop] remove mcscriptStop