#######
# Compiled from .//functions/forEach.mcscript
# to functions/mcscript/foreach3.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players operation result result *= i i
scoreboard players add j j 1
execute if entity @s[tag=!mcscriptStop] if score j j matches ..10 run function :mcscript/foreach3
tag @s[tag=mcscriptStop] remove mcscriptStop
