#######
# Compiled from .//functions/file Setup.mcscript
# to .//functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless entity @e[tag=mcscriptTags] at @p run summon armor_stand ~ ~ ~ {Tags:[mcscriptTags],Invisible:1,Invulnerable:1,NoGravity:1}

# Extended from .//functions/forEach.mcscript
# to functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add i dummy
scoreboard objectives add result dummy
scoreboard objectives add j dummy

# Extended from .//functions/switches.mcscript
# to functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add test dummy

# Extended from .//functions/variables.mcscript
# to functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add var1 dummy
scoreboard objectives add var2 dummy

# Extended from .//functions/raycasting.mcscript
# to functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add raycast4 dummy
