#######
# Compiled from examples/functions/file Setup.mcscript
# to examples/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
r!
execute unless entity @e[tag=mcscriptTags] at @p run summon armor_stand ~ ~ ~ {Tags:[mcscriptTags],Invisible:1,Invulnerable:1,NoGravity:1}

# Extended from examples/functions/forEach.mcscript
# to examples/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add i dummy
scoreboard objectives add result dummy
scoreboard objectives add j dummy

# Extended from examples/functions/raycasting.mcscript
# to examples/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add mcscript_raycast dummy

# Extended from examples/functions/variables.mcscript
# to examples/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add var1 dummy
scoreboard objectives add var2 dummy

# Extended from examples/functions/switches.mcscript
# to examples/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add test dummy
