#######
# Compiled from /examples/functions/raycasting.mcscript
# to examples/functions/mcscript/raycast2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle flame ~ ~ ~
scoreboard players add raycast2 raycast2 1
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run setblock ~ ~ ~ stone
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run tag @s add mcscriptStop
execute positioned ^ ^ ^1 if entity @s[tag=!mcscriptStop] if block ~ ~ ~ air if score raycast2 raycast2 matches ..10 run function examples:mcscript/raycast2
tag @s[tag=mcscriptStop] remove mcscriptStop