#######
# Compiled from .//functions/raycasting.mcscript
# to functions/mcscript/raycast4.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle flame ~ ~ ~
scoreboard players add raycast4 raycast4 1
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run setblock ~ ~ ~ stone
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run tag @s add mcscriptStop
execute positioned ^ ^ ^1 if entity @s[tag=!mcscriptStop] if block ~ ~ ~ air if score raycast4 raycast4 matches ..10 run function :mcscript/raycast4
tag @s[tag=mcscriptStop] remove mcscriptStop