#######
# Compiled from /examples/functions/raycasting.mcscript
# to examples/functions/mcscript/raycast5.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle flame ~ ~ ~
scoreboard players add raycast5 raycast5 1
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run setblock ~ ~ ~ stone
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run tag @s add mcscriptStop
execute positioned ^ ^ ^1 if entity @s[tag=!mcscriptStop] if block ~ ~ ~ air if score raycast5 raycast5 matches ..10 run function examples:mcscript/raycast5
tag @s[tag=mcscriptStop] remove mcscriptStop