#######
# Compiled from .//functions/while-Loops.mcscript
# to functions/mcscript/while5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tellraw @a [{"text":"console => ","color":"aqua"},{"text":"commands","color":"white"}]
execute if entity @s[tag=!mcscriptStop] if entity @s[tag=loop] run function :mcscript/while5
tag @s[tag=mcscriptStop] remove mcscriptStop
